[tool.poetry]
name = "code-agent"
version = "0.1.0"
description = ""
authors = ["Shingo Morimoto <shingo@wolfssl.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
